export const basePrompt = `
<boltArtifact id="project-import" title="Project Files">
  <boltAction type="file" filePath="package.json">
    {
      "name": "nextjs-app",
      "version": "0.1.0",
      "private": true,
      "scripts": {
        "dev": "next dev",
        "build": "next build",
        "start": "next start"
      },
      "dependencies": {
        "react": "^18.3.1",
        "react-dom": "^18.3.1",
        "next": "14.2.3",
        "lucide-react": "^0.378.0",
        "clsx": "^2.1.1",
        "tailwind-merge": "^2.3.0"
      },
      "devDependencies": {
        "typescript": "^5.4.5",
        "@types/node": "^20.12.12",
        "@types/react": "^18.3.2",
        "@types/react-dom": "^18.3.0",
        "postcss": "^8.4.38",
        "tailwindcss": "^3.4.3"
      }
    }
  </boltAction>
  <boltAction type="file" filePath="tsconfig.json">
    {
      "compilerOptions": {
        "lib": ["dom", "dom.iterable", "esnext"],
        "allowJs": true,
        "skipLibCheck": true,
        "strict": true,
        "noEmit": true,
        "esModuleInterop": true,
        "module": "esnext",
        "moduleResolution": "bundler",
        "resolveJsonModule": true,
        "isolatedModules": true,
        "jsx": "preserve",
        "incremental": true,
        "plugins": [
          {
            "name": "next"
          }
        ],
        "paths": {
          "@/*": ["./*"]
        }
      },
      "include": ["next-env.d.ts", "**/*.ts", "**/*.tsx", ".next/types/**/*.ts"],
      "exclude": ["node_modules"]
    }
  </boltAction>
  <boltAction type="file" filePath="next.config.mjs">
    /** @type {import('next').NextConfig} */
    const nextConfig = {};

    export default nextConfig;
  </boltAction>
  <boltAction type="file" filePath="postcss.config.js">
    module.exports = {
      plugins: {
        tailwindcss: {},
        autoprefixer: {},
      },
    };
  </boltAction>
  <boltAction type="file" filePath="tailwind.config.ts">
    import type { Config } from "tailwindcss";

    const config: Config = {
      content: [
        "./pages/**/*.{js,ts,jsx,tsx,mdx}",
        "./components/**/*.{js,ts,jsx,tsx,mdx}",
        "./app/**/*.{js,ts,jsx,tsx,mdx}",
      ],
      theme: {
        extend: {},
      },
      plugins: [],
    };
    export default config;
  </boltAction>
  <boltAction type="file" filePath="app/globals.css">
    @tailwind base;
    @tailwind components;
    @tailwind utilities;

    :root {
      --foreground-rgb: 0, 0, 0;
      --background-start-rgb: 214, 219, 220;
      --background-end-rgb: 255, 255, 255;
    }

    @media (prefers-color-scheme: dark) {
      :root {
        --foreground-rgb: 255, 255, 255;
        --background-start-rgb: 0, 0, 0;
        --background-end-rgb: 0, 0, 0;
      }
    }

    body {
      color: rgb(var(--foreground-rgb));
      background: linear-gradient(
          to bottom,
          transparent,
          rgb(var(--background-end-rgb))
        )
        rgb(var(--background-start-rgb));
    }

    @layer utilities {
      .text-balance {
        text-wrap: balance;
      }
    }
  </boltAction>
  <boltAction type="file" filePath="app/layout.tsx">
    import type { Metadata } from "next";
    import { Inter } from "next/font/google";
    import "./globals.css";

    const inter = Inter({ subsets: ["latin"] });

    export const metadata: Metadata = {
      title: "Create Next App",
      description: "Generated by create next app",
    };

    export default function RootLayout({
      children,
    }: Readonly<{
      children: React.ReactNode;
    }>) {
      return (
        <html lang="en">
          <body className={inter.className}>{children}</body>
        </html>
      );
    }
  </boltAction>
  <boltAction type="file" filePath="app/page.tsx">
    export default function Home() {
      return (
        <main className="flex min-h-screen flex-col items-center justify-between p-24">
          <div className="z-10 w-full max-w-5xl items-center justify-between font-mono text-sm lg:flex">
            <p className="fixed left-0 top-0 flex w-full justify-center border-b border-gray-300 bg-gradient-to-b from-zinc-200 pb-6 pt-8 backdrop-blur-2xl dark:border-neutral-800 dark:bg-zinc-800/30 dark:from-inherit lg:static lg:w-auto  lg:rounded-xl lg:border lg:bg-gray-200 lg:p-4 lg:dark:bg-zinc-800/30">
              Get started by editing&nbsp;
              <code className="font-mono font-bold">app/page.tsx</code>
            </p>
          </div>
        </main>
      );
    }
  </boltAction>
  <boltAction type="shell">
    npm install
  </boltAction>
  <boltAction type="shell">
    npm run dev
  </boltAction>
</boltArtifact>
`;
